In [3]:
import numpy as np

## Vector

In [4]:
v = np.array([3, 2])
w = np.array([1, 4])

In [5]:
print(v+w)

[4 6]


In [6]:
print(2 * v)

[6 4]


**Magnitude (Length):**

$$\|\vec{v}\| = \sqrt{v_1^2 + v_2^2 + \dots + v_n^2}$$

In [7]:
print(round(np.linalg.norm(v), 4))

3.6056


**A Unit Vector**

$$\hat{v} = \frac{\vec{v}}{\|\vec{v}\|}$$

In [8]:
print(v/np.linalg.norm(v))

[0.83205029 0.5547002 ]


### Dot Product



$$\vec{a} \cdot \vec{b} = \|\vec{a}\| \cdot \|\vec{b}\| \cdot \cos\theta$$

where $\theta$ is the angle between the two vectors.

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

### Dot product — three equivalent ways


In [10]:
print(np.dot(a, b))

32


In [11]:
print(a @ b)

32


In [12]:
print(np.sum(a * b))

32


## Cosine Similiarity

$\text{sim}(\vec{a}, \vec{b}) = \frac{\vec{a} \cdot \vec{b}}{\|\vec{a}\| \|\vec{b}\|}$

In [13]:
cos__sim = a @ b / (np.linalg.norm(a) * np.linalg.norm(b))
print(round(cos__sim, 3))

0.975


## Matrix

In [14]:
A = np.array([[3, 2], 
              [2, 5]])
v = np.array([5, 1])

In [15]:
print(A @ v)

[17 15]


### Transpose

In [16]:
print(A.T)

[[3 2]
 [2 5]]


### Indentity matrix

In [17]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Inverse if exist

In [18]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545 -0.18181818]
 [-0.18181818  0.27272727]]


In [19]:
print(A_inv @ A)

[[ 1.00000000e+00 -2.77555756e-17]
 [ 0.00000000e+00  1.00000000e+00]]


### Matrix multiplication

In [21]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
C = A @ B
C = np.matmul(A, B)
# C = np.dot(A, B)

In [27]:
C

array([[19, 22],
       [43, 50]])

In [ ]:
# Verify AB ≠ BA
print(A @ B)
print(B @ A) # different

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


### Deteminants


$$\det\begin{bmatrix} a & b \\ c & d \end{bmatrix} = ad - bc$$

In [31]:
A = np.array([[3, 1],
              [0, 2]])

In [33]:
print(np.linalg.det(A))

6.0


# Linear System

$$\vec{x} = A^{-1}\vec{b}$$

#### Solve: 2x + y = 5, x + 3y = 7

In [35]:
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 7])

In [39]:
x = np.linalg.solve(A, b)
print(x)

[1.6 1.8]


## Eigenvalues & Eigenvectors

$$A\vec{v} = \lambda\vec{v}$$

- $\vec{v}$ is an **eigenvector** — a direction that doesn't change
- $\lambda$ (lambda) is an **eigenvalue** — how much it gets scaled


In [40]:
A = np.array([[3, 1], [0, 2]])

In [46]:
eigen_values, eigen_vectors = np.linalg.eig(A)

In [47]:
print("Eigen Value \n", eigen_values)
print("Eigen Vector \n", eigen_vectors)

Eigen Value 
 [3.+0.j 2.+0.j]
Eigen Vector 
 [[ 1.        +0.j -0.70710678+0.j]
 [ 0.        +0.j  0.70710678+0.j]]


In [54]:
v = eigen_vectors[:, 0]
λ = eigen_values[0]

In [56]:
print("A @ v",  A @ v)
print("λ * v", λ * v)

A @ v [3.+0.j 0.+0.j]
λ * v [3.+0.j 0.+0.j]


### Eigendecomposition

If $A$ has $n$ linearly independent eigenvectors, you can decompose it as:

$$A = V \Lambda V^{-1}$$

where:
- $V$ = matrix whose columns are the eigenvectors
- $\Lambda$ = diagonal matrix of eigenvalues

In [57]:
S = np.array([[4, 2], 
              [2, 3]])

In [58]:
eigenvalues, eigenvectors = np.linalg.eig(S)

In [62]:
V = eigenvectors
Lambda = np.diag(eigenvalues)
A_reconstructed = V @ Lambda @ np.linalg.inv(V)
print(A_reconstructed) # = S

[[4.+0.j 2.+0.j]
 [2.+0.j 3.+0.j]]


## Singular Value Decomposition

SVD is arguably the most important matrix decomposition. It works on **any** matrix — any shape, any rank. Here's the decomposition:

$$A = U \Sigma V^T$$

where:
- $A$ is your $m \times n$ matrix
- $U$ is $m \times m$ orthogonal (columns = **left singular vectors**)
- $\Sigma$ is $m \times n$ diagonal (the **singular values** $\sigma_1 \geq \sigma_2 \geq \dots \geq 0$)
- $V^T$ is $n \times n$ orthogonal (rows = **right singular vectors**)